import type { CRMData } from './types';

export const CRM_DATA: CRMData = {
  contractor: {
    name: 'Mike Delgado',
    business: 'Delgado Home Repair',
    trade: 'Handyman / Remodeling',
    truck: '2018 F-150',
  },

  customers: [
    { id: 'c1', name: 'Patricia Nguyen',   phone: '(415) 555-0142', address: '2214 Fulton St, San Francisco',  jobs: 3, since: '2023' },
    { id: 'c2', name: 'Marcus Johnson',    phone: '(510) 555-0187', address: '1847 Alcatraz Ave, Berkeley',     jobs: 1, since: '2025' },
    { id: 'c3', name: 'Sarah & Tom Weiss', phone: '(415) 555-0203', address: '89 Laidley St, San Francisco',    jobs: 5, since: '2022' },
    { id: 'c4', name: 'Denise Park',       phone: '(650) 555-0176', address: '1120 El Camino Real, San Mateo',  jobs: 2, since: '2024' },
    { id: 'c5', name: 'Gus Morales',       phone: '(415) 555-0115', address: '3301 Mission St, San Francisco',  jobs: 8, since: '2021' },
    { id: 'c6', name: 'Kelsey Bauer',      phone: '(415) 555-0299', address: '515 Clipper St, San Francisco',   jobs: 1, since: '2026' },
  ],

  jobs: [
    {
      id: 'j1',
      title: 'Kitchen cabinet install',
      customer: 'Patricia Nguyen',
      customerId: 'c1',
      address: '2214 Fulton St',
      status: 'in-progress',
      scheduled: 'Today · 9:00 AM',
      due: 'Apr 29',
      price: 2850,
      hours: 4.5,
      hoursEst: 12,
      photos: 7,
      notes: 3,
      materials: 6,
      desc: 'Install 8 upper cabinets, crown molding, under-cabinet LED strip. Customer providing hardware.',
    },
    {
      id: 'j2',
      title: 'Bathroom faucet + vanity',
      customer: 'Marcus Johnson',
      customerId: 'c2',
      address: '1847 Alcatraz Ave',
      status: 'scheduled',
      scheduled: 'Tomorrow · 8:00 AM',
      due: 'Apr 30',
      price: 920,
      hours: 0,
      hoursEst: 5,
      photos: 2,
      notes: 1,
      materials: 3,
      desc: "Replace leaky Moen faucet, install new 36\" vanity top. Shut-off valves may need replacing.",
    },
    {
      id: 'j3',
      title: 'Deck board replacement',
      customer: 'Sarah & Tom Weiss',
      customerId: 'c3',
      address: '89 Laidley St',
      status: 'quote-sent',
      scheduled: 'Waiting on approval',
      due: 'May 2',
      price: 4200,
      hours: 0,
      hoursEst: 22,
      photos: 12,
      notes: 2,
      materials: 14,
      desc: 'Replace 40 rotted deck boards, re-stain full deck. Pressure-treated pine, semi-transparent cedar.',
    },
    {
      id: 'j4',
      title: 'Garage door opener',
      customer: 'Denise Park',
      customerId: 'c4',
      address: '1120 El Camino Real',
      status: 'done',
      scheduled: 'Apr 24',
      due: 'Apr 24',
      price: 485,
      hours: 2.25,
      hoursEst: 2.5,
      photos: 4,
      notes: 2,
      materials: 2,
      desc: 'Replaced LiftMaster 8500 with new WiFi-enabled 8550W. Set up MyQ app.',
    },
    {
      id: 'j5',
      title: 'Fence post + gate repair',
      customer: 'Gus Morales',
      customerId: 'c5',
      address: '3301 Mission St',
      status: 'done',
      scheduled: 'Apr 22',
      due: 'Apr 22',
      price: 680,
      hours: 3,
      hoursEst: 3,
      photos: 6,
      notes: 1,
      materials: 4,
      desc: 'Dug out two rotted 4x4 posts, set new ones in concrete. Rehung gate, replaced latch.',
    },
    {
      id: 'j6',
      title: 'Recessed lighting — dining room',
      customer: 'Kelsey Bauer',
      customerId: 'c6',
      address: '515 Clipper St',
      status: 'new',
      scheduled: 'Needs scheduling',
      due: 'May 6',
      price: 0,
      hours: 0,
      hoursEst: 6,
      photos: 0,
      notes: 1,
      materials: 0,
      desc: 'Walk-through requested. 6 cans in dining room, dimmer switch. Ceiling is plaster.',
    },
  ],

  materials: [
    { id: 1, jobId: 'j1', name: 'Hampton white cabinets (8)',   qty: '8 ea',     cost: 1240, supplier: 'Home Depot',    got: true  },
    { id: 2, jobId: 'j1', name: '3/4" oak plywood',             qty: '2 sheets', cost: 186,  supplier: 'Central Lumber', got: true  },
    { id: 3, jobId: 'j1', name: 'Cabinet screws 2.5"',          qty: '1 box',    cost: 18,   supplier: 'Home Depot',    got: true  },
    { id: 4, jobId: 'j1', name: "Crown molding, oak 8'",        qty: '4 pcs',    cost: 84,   supplier: 'Central Lumber', got: false },
    { id: 5, jobId: 'j1', name: "Under-cabinet LED strip 16'",  qty: '1 kit',    cost: 65,   supplier: 'Amazon',        got: false },
    { id: 6, jobId: 'j1', name: 'Wire nuts, misc',              qty: '1 pack',   cost: 12,   supplier: 'Truck stock',   got: true  },
  ],

  timeline: [
    { when: '9:12 AM',  who: 'Mike',     what: 'Arrived on-site',                                                   kind: 'status' },
    { when: '9:34 AM',  who: 'Mike',     what: 'Photo: existing wall condition',                                     kind: 'photo',   n: 2 },
    { when: '10:20 AM', who: 'Mike',     what: 'Note: Found old wiring behind top-left cabinet — will need to re-route. +30 min.', kind: 'note' },
    { when: '11:45 AM', who: 'Mike',     what: 'Photo: first 3 cabinets mounted',                                    kind: 'photo',   n: 3 },
    { when: '12:30 PM', who: 'Patricia', what: 'Text: "Can you pick up the hardware? I forgot."',                    kind: 'message' },
    { when: '1:15 PM',  who: 'Mike',     what: 'Voice memo · 0:42',                                                  kind: 'voice' },
    { when: '2:40 PM',  who: 'Mike',     what: 'Photo: crown molding up',                                            kind: 'photo',   n: 2 },
  ],

  todaySchedule: [
    { time: '9:00 AM',  title: 'Kitchen cabinet install', who: 'Patricia Nguyen', addr: '2214 Fulton St',     tag: 'in-progress' },
    { time: '2:00 PM',  title: 'Supply run',              who: 'Central Lumber',  addr: '1301 Bayshore Blvd', tag: 'errand' },
    { time: '3:30 PM',  title: 'Walk-through',            who: 'Kelsey Bauer',    addr: '515 Clipper St',     tag: 'quote' },
  ],
};
